### ISSUE TITLE
Incorrect property.

### ISSUE THREAD

**Issue by Jdance-Media** [SlothsAreLazyTho/Pterodactyl.NET#1]
![image](https://github.com/SlothsAreLazyTho/Pterodactyl.NET/assets/67397422/a11fd058-cb97-4290-b87d-d739ff59fba9)
Solution: take out a dictionary, read it, and then change it to maintenance.

**Comment by Jdance-Media** [comment]
This package is actually useful, so if it could get some love that would be nice.

**Comment by SlothsAreLazyTho** [comment]
Sorry for the late response. I'm open to PRs, I honestly wasn't expecting people using the wrapper.

**Comment by Jdance-Media** [comment]
Alright, I suppose I'll make a PR 👍

**Comment by SlothsAreLazyTho** [comment]
I made a fix for it, I'll push the files this evening 👍

**Comment by SlothsAreLazyTho** [comment]
Issue should be solved now, Tomorrow the NuGet page will be updated so you can bump your version to the latest version✅
